spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sds_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.wuhan.tracedemo.controller: DEBUG
    com.wuhan.tracedemo.mapper: DEBUG
    org.apache.ibatis: DEBUG
    org.springfromework.web: INFO
  file: logs/spring-boot-logging.log
server:
  port: 8019

